### ISSUE TITLE
Proposal: Add `dep` as commit message `type` option

### ISSUE THREAD

**Issue by cromwellryan** [sparkbox/standard#40]
I find myself upgrading an npm or ruby dependency and feeling really weird about using `feat`.  I feel like a unique `dep` type might help:

Examples:

```
dep: upgrade grunt to version 0.4.5

This version brings magical unicorn spit for slippery
fast concats on large directories like ./js.  This required 
an options update to the concat task: `useUnicornSaliva: true`.
```

```
dep: upgrade ActiveRecord to 2.1.666

We ran into a bug with outer joins via Arel tables
that is resolved in this incremental build.  
```

**Comment by yock** [comment]
I usually use `chore` for stuff like this. Dependency upgrades might be significant enough to warrant their own prefix though.

**Comment by cromwellryan** [comment]
That was my thought.  Chore specifically says _not production code_.

**Comment by dflynn15** [comment]
That seems much more clear. May I also suggest that the :exclamation: emoji tags along as our visual friend?
