### ISSUE TITLE
Clarify `style` value for <type>

### ISSUE THREAD

**Issue by timkelty** [sparkbox/standard#53]
"no code change"...I'm wondering where this leaves css changes.
Do you consider that "code"?

`feat: style admin layout`
vs.
`style: admin layout`

**Comment by cromwellryan** [comment]
Great question! Style would apply to code style. Brackets, spacing , etc.
We totally consider Css code. We build features with css, refactor css,
document css ...

On Wednesday, April 27, 2016, Tim Kelty <notifications@github.com> wrote:

> "no code change"...I'm wondering where this leaves css changes.
> Do you consider that "code"?
>
> feat: style admin layout
> vs.
> style: admin layout
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sparkbox/standard/issues/53>
>


-- 


*Ryan Cromwell**Sparkbox*
123 Webster Street, Studio 2
Dayton, OH 45402
937.401.0915 · calendar
<http://www.google.com/calendar/embed?src=ryan%40heysparkbox.com&ctz=America/New_York>
www.seesparkbox.com

**Comment by timkelty** [comment]
That's what I figured, thanks!
One other related question:

The only time I've been questioning which `<type>` to use so far is early in a project, when you aren't necessarily "adding features", but just getting things set up and off the ground. Do you still consider these `feat`?

Examples:
`feat: initial styles`
`feat: install cms`
`feat: forms look usable`

**Comment by yock** [comment]
Installing the CMS I'd label as `chore` since it's just a task that needs completed. I'd love to hear what others think about your other two, but I suspect that work can usually be broken down into smaller, more meaningful pieces.

**Comment by timkelty** [comment]
I'm sure you certainly could break them down. I think with CSS especially, theres a certain level of work to be done before you have a base to establish features on. That said, maybe tagging that stuff `feat` is still fine.

If you think about the lifecycle of a piece of code in context of these tags, I think its this first step I'm trying to describe:

'<initial "factoring">' → `feat ` → `refactor`

Maybe the distinction isn't important, though.

**Comment by catheraaine** [comment]
Hey Tim! Since this issue is over a year old, I'm closing it, but thank you for the comments!
